import OPTION_IDS from "../colour/optionIds";
import { StepOptionImage } from "./types";

export const STEP_OPTION_IMAGES: StepOptionImage[] = [
  
  // Default images per house type
  { image_url: "../../../assets/detached.jpg", options: [OPTION_IDS.HOUSE.DETACHED] },
  { image_url: "../../../assets/semi-detached.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED] },
  { image_url: "../../../assets/terraced.jpg", options: [OPTION_IDS.HOUSE.TERRACED] },

  // HOUSE PREVIEW - BRICK SLIPS - DETACHED
  { image_url: "../../../assets/detached_brick_slips/sahara.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.SAHARA] },
  { image_url: "../../../assets/detached_brick_slips/blackpool.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.BLACKPOOL] },
  { image_url: "../../../assets/detached_brick_slips/colorado.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLORADO] },
  { image_url: "../../../assets/detached_brick_slips/cordoba.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.CORDOBA] },
  { image_url: "../../../assets/detached_brick_slips/corsica.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.CORSICA] },
  { image_url: "../../../assets/detached_brick_slips/nebraska.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.NEBRASKA] },
  { image_url: "../../../assets/detached_brick_slips/malta.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.MALTA] },
  { image_url: "../../../assets/detached_brick_slips/alaska.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.ALASKA] },
  { image_url: "../../../assets/detached_brick_slips/glasgow.jpg", options: [ OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.GLASGOW] },

  // HOUSE PREVIEW - BRICK SLIPS - SEMI-DETACHED
  { image_url: "../../../assets/semi-detached_brick_slips/sahara.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.SAHARA] },
  { image_url: "../../../assets/semi-detached_brick_slips/blackpool.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.BLACKPOOL] },
  { image_url: "../../../assets/semi-detached_brick_slips/colorado.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLORADO] },
  { image_url: "../../../assets/semi-detached_brick_slips/cordoba.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.CORDOBA] },
  { image_url: "../../../assets/semi-detached_brick_slips/corsica.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.CORSICA] },
  { image_url: "../../../assets/semi-detached_brick_slips/nebraska.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.NEBRASKA] },
  { image_url: "../../../assets/semi-detached_brick_slips/malta.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.MALTA] },
  { image_url: "../../../assets/semi-detached_brick_slips/alaska.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.ALASKA] },
  { image_url: "../../../assets/semi-detached_brick_slips/glasgow.jpg", options: [ OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.GLASGOW] },
  

  // HOUSE PREVIEW - BRICK SLIPS - TERRACED
  { image_url: "../../../assets/terraced_brick_slips/sahara.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.SAHARA] },
  { image_url: "../../../assets/terraced_brick_slips/blackpool.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.BLACKPOOL] },
  { image_url: "../../../assets/terraced_brick_slips/colorado.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLORADO] },
  { image_url: "../../../assets/terraced_brick_slips/cordoba.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.CORDOBA] },
  { image_url: "../../../assets/terraced_brick_slips/corsica.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.CORSICA] },
  { image_url: "../../../assets/terraced_brick_slips/nebraska.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.NEBRASKA] },
  { image_url: "../../../assets/terraced_brick_slips/malta.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.MALTA] },
  { image_url: "../../../assets/terraced_brick_slips/alaska.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.ALASKA] },
  { image_url: "../../../assets/terraced_brick_slips/glasgow.jpg", options: [ OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.GLASGOW] },

  // HOUSE PREVIEW - RENDER COLOURS - DETACHED
  { image_url: "../../../assets/detached_renders/10001-Brilliant_White.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_10001] },
  { image_url: "../../../assets/detached_renders/20001-Pure_White.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_20001_PURE_WHITE] },
  { image_url: "../../../assets/detached_renders/20001.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_20001] },
  { image_url: "../../../assets/detached_renders/20168-Paraffin.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_20168] },
  { image_url: "../../../assets/detached_renders/21189-Peach.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_21189] },
  { image_url: "../../../assets/detached_renders/22219-Peony.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_22219] },
  { image_url: "../../../assets/detached_renders/22440-Rose.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_22440] },
  { image_url: "../../../assets/detached_renders/22594-Coral.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_22594] },
  { image_url: "../../../assets/detached_renders/23544-Elderflower.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_23544] },
  { image_url: "../../../assets/detached_renders/24194-Mirror.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_24194] },
  { image_url: "../../../assets/detached_renders/25070-Sage.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_25070] },
  { image_url: "../../../assets/detached_renders/25820-Prosecco.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_25820] },
  { image_url: "../../../assets/detached_renders/26470-Silk.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_26470] },
  { image_url: "../../../assets/detached_renders/27037-Acorn.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27037] },
  { image_url: "../../../assets/detached_renders/27041-Truffle.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27041] },
  { image_url: "../../../assets/detached_renders/27116-Storm.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27116] },
  { image_url: "../../../assets/detached_renders/27120-Silver.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27120] },
  { image_url: "../../../assets/detached_renders/27254-Walnut.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27254] },
  { image_url: "../../../assets/detached_renders/27408-Steel.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27408] },
  { image_url: "../../../assets/detached_renders/27412-Ash.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27412] },
  { image_url: "../../../assets/detached_renders/27416-Smoke.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27416] },
  { image_url: "../../../assets/detached_renders/27420-Diamond.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27420] },
  { image_url: "../../../assets/detached_renders/27491-Concrete.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27491] },
  { image_url: "../../../assets/detached_renders/27495-Fog.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27495] },
  { image_url: "../../../assets/detached_renders/27554-Lead.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27554] },
  { image_url: "../../../assets/detached_renders/27566-Cloud.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27566] },
  { image_url: "../../../assets/detached_renders/27570-Clay.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_27570] },
  { image_url: "../../../assets/detached_renders/28010-Porcelain.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28010] },
  { image_url: "../../../assets/detached_renders/28012-Bone.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28012] },
  { image_url: "../../../assets/detached_renders/28014-Haze.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28014] },
  { image_url: "../../../assets/detached_renders/28018-Ivory.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28018] },
  { image_url: "../../../assets/detached_renders/28028-Eggshell.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28028] },
  { image_url: "../../../assets/detached_renders/28030-Almond.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28030] },
  { image_url: "../../../assets/detached_renders/28036-Magnolia.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28036] },
  { image_url: "../../../assets/detached_renders/28038-Mist.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28038] },
  { image_url: "../../../assets/detached_renders/28048-Linen.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28048] },
  { image_url: "../../../assets/detached_renders/28050-Frost.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28050] },
  { image_url: "../../../assets/detached_renders/28056-Opal.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28056] },
  { image_url: "../../../assets/detached_renders/28058-Ice.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28058] },
  { image_url: "../../../assets/detached_renders/28070-Sandstone.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28070] },
  { image_url: "../../../assets/detached_renders/28076-Antique_White.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28076] },
  { image_url: "../../../assets/detached_renders/28078-Copenhagen.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28078] },
  { image_url: "../../../assets/detached_renders/28080-Platinum.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28080] },
  { image_url: "../../../assets/detached_renders/28088-Orchid.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_28088] },
  { image_url: "../../../assets/detached_renders/29050-Seashell.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_29050] },
  { image_url: "../../../assets/detached_renders/29315-Dune.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_29315] },
  { image_url: "../../../assets/detached_renders/29710-HailStone.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_29710] },
  { image_url: "../../../assets/detached_renders/29740-Anthracite.jpg", options: [OPTION_IDS.HOUSE.DETACHED, OPTION_IDS.COLOURS.COLOR_29740] },

  // HOUSE PREVIEW - RENDER COLOURS - SEMI-DETACHED
  { image_url: "../../../assets/semi-detached_renders/10001-Brilliant_White.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_10001] },
  { image_url: "../../../assets/semi-detached_renders/20001-Pure_White.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_20001_PURE_WHITE] },
  { image_url: "../../../assets/semi-detached_renders/20001.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_20001] },
  { image_url: "../../../assets/semi-detached_renders/20168-Paraffin.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_20168] },
  { image_url: "../../../assets/semi-detached_renders/21189-Peach.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_21189] },
  { image_url: "../../../assets/semi-detached_renders/22219-Peony.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_22219] },
  { image_url: "../../../assets/semi-detached_renders/22440-Rose.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_22440] },
  { image_url: "../../../assets/semi-detached_renders/22594-Coral.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_22594] },
  { image_url: "../../../assets/semi-detached_renders/23544-Elderflower.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_23544] },
  { image_url: "../../../assets/semi-detached_renders/24194-Mirror.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_24194] },
  { image_url: "../../../assets/semi-detached_renders/25070-Sage.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_25070] },
  { image_url: "../../../assets/semi-detached_renders/25820-Prosecco.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_25820] },
  { image_url: "../../../assets/semi-detached_renders/26470-Silk.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_26470] },
  { image_url: "../../../assets/semi-detached_renders/27037-Acorn.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27037] },
  { image_url: "../../../assets/semi-detached_renders/27041-Truffle.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27041] },
  { image_url: "../../../assets/semi-detached_renders/27116-Storm.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27116] },
  { image_url: "../../../assets/semi-detached_renders/27120-Silver.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27120] },
  { image_url: "../../../assets/semi-detached_renders/27254-Walnut.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27254] },
  { image_url: "../../../assets/semi-detached_renders/27408-Steel.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27408] },
  { image_url: "../../../assets/semi-detached_renders/27412-Ash.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27412] },
  { image_url: "../../../assets/semi-detached_renders/27416-Smoke.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27416] },
  { image_url: "../../../assets/semi-detached_renders/27420-Diamond.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27420] },
  { image_url: "../../../assets/semi-detached_renders/27491-Concrete.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27491] },
  { image_url: "../../../assets/semi-detached_renders/27495-Fog.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27495] },
  { image_url: "../../../assets/semi-detached_renders/27554-Lead.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27554] },
  { image_url: "../../../assets/semi-detached_renders/27566-Cloud.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27566] },
  { image_url: "../../../assets/semi-detached_renders/27570-Clay.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_27570] },
  { image_url: "../../../assets/semi-detached_renders/28010-Porcelain.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28010] },
  { image_url: "../../../assets/semi-detached_renders/28012-Bone.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28012] },
  { image_url: "../../../assets/semi-detached_renders/28014-Haze.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28014] },
  { image_url: "../../../assets/semi-detached_renders/28018-Ivory.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28018] },
  { image_url: "../../../assets/semi-detached_renders/28028-Eggshell.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28028] },
  { image_url: "../../../assets/semi-detached_renders/28030-Almond.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28030] },
  { image_url: "../../../assets/semi-detached_renders/28036-Magnolia.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28036] },
  { image_url: "../../../assets/semi-detached_renders/28038-Mist.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28038] },
  { image_url: "../../../assets/semi-detached_renders/28048-Linen.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28048] },
  { image_url: "../../../assets/semi-detached_renders/28050-Frost.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28050] },
  { image_url: "../../../assets/semi-detached_renders/28056-Opal.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28056] },
  { image_url: "../../../assets/semi-detached_renders/28058-Ice.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28058] },
  { image_url: "../../../assets/semi-detached_renders/28070-Sandstone.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28070] },
  { image_url: "../../../assets/semi-detached_renders/28076-Antique_White.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28076] },
  { image_url: "../../../assets/semi-detached_renders/28078-Copenhagen.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28078] },
  { image_url: "../../../assets/semi-detached_renders/28080-Platinum.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28080] },
  { image_url: "../../../assets/semi-detached_renders/28088-Orchid.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_28088] },
  { image_url: "../../../assets/semi-detached_renders/29050-Seashell.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_29050] },
  { image_url: "../../../assets/semi-detached_renders/29315-Dune.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_29315] },
  { image_url: "../../../assets/semi-detached_renders/29710-HailStone.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_29710] },
  { image_url: "../../../assets/semi-detached_renders/29740-Anthracite.jpg", options: [OPTION_IDS.HOUSE.SEMI_DETACHED, OPTION_IDS.COLOURS.COLOR_29740] },

    // HOUSE PREVIEW - RENDER COLOURS - TERRACED
  { image_url: "../../../assets/terraced_renders/10001-Brilliant_White.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_10001] },
  { image_url: "../../../assets/terraced_renders/20001-Pure_White.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_20001_PURE_WHITE] },
  { image_url: "../../../assets/terraced_renders/20001.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_20001] },
  { image_url: "../../../assets/terraced_renders/20168-Paraffin.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_20168] },
  { image_url: "../../../assets/terraced_renders/21189-Peach.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_21189] },
  { image_url: "../../../assets/terraced_renders/22219-Peony.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_22219] },
  { image_url: "../../../assets/terraced_renders/22440-Rose.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_22440] },
  { image_url: "../../../assets/terraced_renders/22594-Coral.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_22594] },
  { image_url: "../../../assets/terraced_renders/23544-Elderflower.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_23544] },
  { image_url: "../../../assets/terraced_renders/24194-Mirror.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_24194] },
  { image_url: "../../../assets/terraced_renders/25070-Sage.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_25070] },
  { image_url: "../../../assets/terraced_renders/25820-Prosecco.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_25820] },
  { image_url: "../../../assets/terraced_renders/26470-Silk.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_26470] },
  { image_url: "../../../assets/terraced_renders/27037-Acorn.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27037] },
  { image_url: "../../../assets/terraced_renders/27041-Truffle.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27041] },
  { image_url: "../../../assets/terraced_renders/27116-Storm.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27116] },
  { image_url: "../../../assets/terraced_renders/27120-Silver.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27120] },
  { image_url: "../../../assets/terraced_renders/27254-Walnut.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27254] },
  { image_url: "../../../assets/terraced_renders/27408-Steel.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27408] },
  { image_url: "../../../assets/terraced_renders/27412-Ash.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27412] },
  { image_url: "../../../assets/terraced_renders/27416-Smoke.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27416] },
  { image_url: "../../../assets/terraced_renders/27420-Diamond.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27420] },
  { image_url: "../../../assets/terraced_renders/27491-Concrete.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27491] },
  { image_url: "../../../assets/terraced_renders/27495-Fog.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27495] },
  { image_url: "../../../assets/terraced_renders/27554-Lead.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27554] },
  { image_url: "../../../assets/terraced_renders/27566-Cloud.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27566] },
  { image_url: "../../../assets/terraced_renders/27570-Clay.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_27570] },
  { image_url: "../../../assets/terraced_renders/28010-Porcelain.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28010] },
  { image_url: "../../../assets/terraced_renders/28012-Bone.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28012] },
  { image_url: "../../../assets/terraced_renders/28014-Haze.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28014] },
  { image_url: "../../../assets/terraced_renders/28018-Ivory.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28018] },
  { image_url: "../../../assets/terraced_renders/28028-Eggshell.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28028] },
  { image_url: "../../../assets/terraced_renders/28030-Almond.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28030] },
  { image_url: "../../../assets/terraced_renders/28036-Magnolia.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28036] },
  { image_url: "../../../assets/terraced_renders/28038-Mist.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28038] },
  { image_url: "../../../assets/terraced_renders/28048-Linen.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28048] },
  { image_url: "../../../assets/terraced_renders/28050-Frost.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28050] },
  { image_url: "../../../assets/terraced_renders/28056-Opal.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28056] },
  { image_url: "../../../assets/terraced_renders/28058-Ice.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28058] },
  { image_url: "../../../assets/terraced_renders/28070-Sandstone.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28070] },
  { image_url: "../../../assets/terraced_renders/28076-Antique_White.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28076] },
  { image_url: "../../../assets/terraced_renders/28078-Copenhagen.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28078] },
  { image_url: "../../../assets/terraced_renders/28080-Platinum.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28080] },
  { image_url: "../../../assets/terraced_renders/28088-Orchid.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_28088] },
  { image_url: "../../../assets/terraced_renders/29050-Seashell.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_29050] },
  { image_url: "../../../assets/terraced_renders/29315-Dune.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_29315] },
  { image_url: "../../../assets/terraced_renders/29710-HailStone.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_29710] },
  { image_url: "../../../assets/terraced_renders/29740-Anthracite.jpg", options: [OPTION_IDS.HOUSE.TERRACED, OPTION_IDS.COLOURS.COLOR_29740] },

];

export default STEP_OPTION_IMAGES;
